# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccf6584a6c11f9dc351c9ff1b1112fdc22f18dabb8a55f7f531013d2c25c0e8e66396b3fe19c6941462bea68cf9cecb5c8fefae65cead147c59c6609e8aa9df3

test:
  secret_key_base: f6f27e2c1677ef97566a8212d02fa36c0124335471afa9d95780981feb830df2715e0691aea988622a6e6032bd61b029a0b759685158c0d6e72367952b8b1029

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
